### ISSUE TITLE
Touchinput in Amiberry GUI

### ISSUE THREAD

**Issue by bspinner** [bspinner/amiberry-android#8]
As a user I want to interact with the Amiberry GUI as long as there's no Android GUI,
so I am able to configure the emulation.

**Comment by bspinner** [comment]
@midwan I'll assign this issue to myself, since I've got a branch where it's working already. Code just needs polishing.

edit: Ah, I just noticed you already applied my patch to your repo :) Then I'll only need to fix the SDL_Window size stuff.

**Comment by midwan** [comment]
This should be fixed with the latest commits, so I'm closing it (unless you discover any issues)
